#!/bin/bash
# Copyright (C) 2021 b1f6c1c4
#
# This file is part of ajnin.
#
# ajnin is free software: you can redistribute it and/or modify it under the
# terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3.
#
# ajnin is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for
# more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with ajnin.  If not, see <https://www.gnu.org/licenses/>.

set -euo pipefail

if [ -f build.ajnin ]; then
    ajnin build.ajnin -o build.ninja
    ninja "$@"
else
    echo '!!!!!!!!! ??WHAT THE FUCK ARE YOU DOING??  !!!!!!!!!' >&2
    exit 114
fi
