#!/bin/bash

set -euo pipefail

if [ -f build.ajnin ]; then
    ajnin build.ajnin -o build.ninja
    ninja "$@"
else
    echo '!!!!!!!!! ??WHAT THE FUCK ARE YOU DOING??  !!!!!!!!!' >&2
    exit 114
fi
