version: 0.5.{build}

skip_tags: true

skip_commits:
  message: /\[ci skip\]|\[skip ci\]/

image: Ubuntu2004

shallow_clone: true
clone_depth: 1

environment:
  COVERALLS_REPO_TOKEN:
    secure: H8M9TzLC1Oxr/sgpj8ZwfYQOgzHoAI48eL2TOTOddAERzfu5nZy7Zb9f/p7mX2y2
  JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64/

install:
  - sudo apt-get update
  - sudo apt-get install -y ninja-build libboost-all-dev antlr4 antlr4-cpp-runtime pandoc pkg-config uuid-dev
  - sudo wget -P /usr/share/java/ https://www.antlr.org/download/antlr-4.13.1-complete.jar

before_build:
  - cmake -S . -B cmake-build-debug -DCMAKE_BUILD_TYPE=Debug -G Ninja

build_script:
  - cmake --build cmake-build-debug
  - cmake --build cmake-build-debug -- manual

test_script:
  - cmake --build cmake-build-debug -- test

after_test:
  - cmake --build cmake-build-debug -- coveralls
